# Generated by Django 5.0.6 on 2024-05-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_media_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
