# Generated by Django 5.0.6 on 2024-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills'),
        ),
    ]
